//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jpmapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class career_faculty
    {
        public int career_faculty_id { get; set; }
        public Nullable<int> career_id { get; set; }
        public Nullable<int> faculty_id { get; set; }
    
        public virtual careers careers { get; set; }
        public virtual faculties faculties { get; set; }
    }
}
