//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jpmapi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jpmEntities : DbContext
    {
        public jpmEntities()
            : base("name=jpmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<career_categories> career_categories { get; set; }
        public virtual DbSet<career_faculty> career_faculty { get; set; }
        public virtual DbSet<careers> careers { get; set; }
        public virtual DbSet<faculties> faculties { get; set; }
        public virtual DbSet<photos> photos { get; set; }
        public virtual DbSet<profesionals> profesionals { get; set; }
        public virtual DbSet<questions> questions { get; set; }
        public virtual DbSet<replies> replies { get; set; }
        public virtual DbSet<user_career> user_career { get; set; }
        public virtual DbSet<user_token> user_token { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<videos> videos { get; set; }
        public virtual DbSet<tests> tests { get; set; }
    }
}
